env: test

port: ":8000"

log:
  logpath: "/Users/wk/Documents/localhost/go/src/gintest/"
  logprefix: "gintest"
  trace: true
  level: 6
  formatter: "json"

mysql:
  dsn: "root:@tcp(192.168.56.2:3306)/gotest"
  max_idle_conn: 100
  max_open_conn: 50
